//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLXEKHACH.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ql_xekhachEntities1 : DbContext
    {
        public ql_xekhachEntities1()
            : base("name=ql_xekhachEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<tBaoTri> tBaoTris { get; set; }
        public DbSet<tChuyen> tChuyens { get; set; }
        public DbSet<tNhienLieu> tNhienLieux { get; set; }
        public DbSet<tPhieuNhienLieu> tPhieuNhienLieux { get; set; }
        public DbSet<tTaiXe> tTaiXes { get; set; }
        public DbSet<tXe> tXes { get; set; }
    }
}
