//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLXEKHACH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tChuyen
    {
        public string MaChuyen { get; set; }
        public string SoXe { get; set; }
        public string MaTaiXe { get; set; }
        public string SoLuongKhach { get; set; }
        public string GioXuatBen { get; set; }
    
        public virtual tTaiXe tTaiXe { get; set; }
        public virtual tXe tXe { get; set; }
    }
}
