//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLXEKHACH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tNhienLieu
    {
        public tNhienLieu()
        {
            this.tPhieuNhienLieux = new HashSet<tPhieuNhienLieu>();
        }
    
        public string MaNhienLieu { get; set; }
        public string TenNhienLieu { get; set; }
        public string DonGia { get; set; }
    
        public virtual ICollection<tPhieuNhienLieu> tPhieuNhienLieux { get; set; }
    }
}
