//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLXEKHACH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPhieuNhienLieu
    {
        public string SoPhieu { get; set; }
        public string NgayLapPhieu { get; set; }
        public string MaNhienLieu { get; set; }
        public string SoLuong { get; set; }
        public string SoXe { get; set; }
    
        public virtual tNhienLieu tNhienLieu { get; set; }
        public virtual tXe tXe { get; set; }
    }
}
